### ISSUE TITLE
Write up how to forward GMail from rcvfortexas.org accounts

### ISSUE THREAD

**Issue by chrisflesher** [rcvfortexas/rcvfortexas#29]
We made some new rcvfortexas.org e-mail accounts. If people don't log into these accounts very often it may be more convenient to synch with their pre-existing e-mail accounts somehow. Need to write up how to do this and verify it works with a few people before sending out the instructions to the whole team.

**Comment by ironunicorn** [comment]
Would it be okay to just refer these people to google's instructions? https://support.google.com/mail/answer/10957?hl=en#zippy=%2Cturn-automatic-fowarding-on-or-off

**Comment by chrisflesher** [comment]
Ok, thanks for putting this together! Added these instructions to the following doc:
https://docs.google.com/document/d/1mtPTu5_Xlxeyy2WhcWMGVPDyGZayLhYQKtMHVfwWeWc/edit
