### ISSUE TITLE
Consolidate tags

### ISSUE THREAD

**Issue by hwasserstrum** [rcvfortexas/rcvfortexas#42]
There are a lot of old tags and some new ones based on the revised volunteer page. The attached file is an attempt to merge tags as appropriate. Existing tags are numbered in column A and suggested merges are indicated by a capital letter in column C. Those tags designated with a capital letter are named in column F. Existing tags that remain are indicated in lower case letters in column c. There is some color coding with comments or questions. Column D just indicates how many records had each tag as of a couple of weeks ago. 
It would probably be wise for me to talk with whoever takes this project to explain the attached file.

[Tags.xlsx](https://github.com/rcvfortexas/rcvfortexas/files/7360920/Tags.xlsx)

**Comment by chrisflesher** [comment]
Here is a good reference for the tag naming system:
https://support.nationbuilder.com/en/articles/2305680-how-to-use-tags

**Comment by chrisflesher** [comment]
@hwasserstrum @ironunicorn is this complete?

**Comment by chrisflesher** [comment]
We have an existing document from Rank the Vote on tag naming conventions:
https://docs.google.com/document/d/1nB5Up22Xs7lbUrWAZGj9MEQktIXTa5PJ/edit

Do you guys think we should update this document for our own system or should we delete it and just point people to use the NationBuilder suggestions? Or something else?
https://support.nationbuilder.com/en/articles/2305680-how-to-use-tags

**Comment by hwasserstrum** [comment]
I think both documents provide some useful information.
    On Saturday, February 12, 2022, 03:15:17 PM CST, chrisflesher ***@***.***> wrote:  
 
 


We have an existing document from Rank the Vote on tag naming conventions:
https://docs.google.com/document/d/1nB5Up22Xs7lbUrWAZGj9MEQktIXTa5PJ/edit

Do you guys think we should update this document for our own system or should we delete it and just point people to use the NationBuilder suggestions? Or something else?
https://support.nationbuilder.com/en/articles/2305680-how-to-use-tags

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hwasserstrum** [comment]
I think there is a problem with how some volunteer tags are getting assigned. People signing up now are getting tags that include 2020 in the name and that shouldn't be happening. How can I see a report that shows for each category on the volunteer page which tag is now getting assigned?  Also, there is some old tag cleanup that still needs to happen.

**Comment by chrisflesher** [comment]
Hey @alexkarjeker thanks for looking at this, here is a link to the remaining work:
https://docs.google.com/spreadsheets/d/1obBoGbWojf9DX9IARIyyu3CI9dfF_cr9/edit?usp=sharing&ouid=102988151650949944855&rtpof=true&sd=true

Also I'm not sure we ever came up with a system for formulating names in the future, if it makes sense to make a doc people can use to enforce naming conventions going forward?

**Comment by hwasserstrum** [comment]
The document Chris linked to is pretty old. I've done a lot of cleanup since then. The new problem I identified in April related to how some old tags were being assigned to new accounts. I think I already cleaned that up too. 
I'd like to try to merge the Take Action and Volunteer pages which would result in further chances to tags so please hold off on this issue. I agree that a document on naming conventions would be good.
If you are available to work on cleanup, highest on my list is Issue #71 to delete everyone who has neither an email address nor a phone number. We recently changed the defaults on Facebook and Twitter additions to our database so fewer people we can't contact are being added. I'd also like to offload people who have unsubscribed but keep their information in a google doc we can access. That way we will stop sending them newsletters and meeting invitations but could still try to contact them when we are trying to reach constituents of specific legislators. At a minimum, save their signup and unsubscribe dates, addresses, and voting districts if present. If it is easy to save their whole record, that would be even better.ThanksHarriet

    On Monday, May 30, 2022, 02:46:43 PM CDT, chrisflesher ***@***.***> wrote:  
 
 


Hey @alexkarjeker thanks for looking at this, here is a link to the remaining work:
https://docs.google.com/spreadsheets/d/1obBoGbWojf9DX9IARIyyu3CI9dfF_cr9/edit?usp=sharing&ouid=102988151650949944855&rtpof=true&sd=true

Also I'm not sure we ever came up with a system for formulating names in the future, if it makes sense to make a doc people can use to enforce naming conventions going forward?

**Comment by chrisflesher** [comment]
Hi Harriet, to close this issue it sounds like we just need to create a document describing existing naming conventions? Anything else? Austin is already working on issue #71.
