### ISSUE TITLE
Investigate Instagram / LinkedIn integration with NationBuilder

### ISSUE THREAD

**Issue by chrisflesher** [rcvfortexas/rcvfortexas#50]
Harriet and Megan can see which users are coming from Facebook and Twitter but not Instagram and LinkedIn. Investigate what tie in there is with these platforms and NationBuilder.

**Comment by chrisflesher** [comment]
Harriet and Megan can see which users are coming from Facebook and Twitter but not Instagram and LinkedIn. Investigate what tie in there is with these platforms and NationBuilder.

**Comment by alexkarjeker** [comment]
NationBuilder has specific integrations between Facebook and Twitter. These types of integrations don't exist for Instagram or LinkedIn.

However, if there are specific actions in NationBuilder (like creating a new contact or adding a contact to a list) that we would like to have occur when certain Instagram actions occur (new media posted), we can set those up in a service called Zapier. (see examples https://zapier.com/apps/instagram/integrations/nationbuilder) 

We should follow up with the team to see if they'd like to try that.

**Comment by chrisflesher** [comment]
Hexel had used IFTTT before (seems similar to Zapier) to automate some stuff for a previous campaign he had worked on.

**Comment by chrisflesher** [comment]
Think the important thing got resolved (setting up tracking for Linkedin / Instagram). It looks like it is possible to do integrations with Zapier or IFTTT if we want to at some point in the future.
