### ISSUE TITLE
Create Thank You page for post-donation

### ISSUE THREAD

**Issue by DJ-Eckam** [rcvfortexas/rcvfortexas#57]

**Comment by DJ-Eckam** [comment]
We need 2 identical pages, for GA tracking purposes -- one for the 501c3 donations and one for 501c4. 

So I'm trying to think of two slugs -- "thank_you" and "thank_you_1" maybe? But @ironunicorn I remember you said you don't like numbers like that in page slugs, and I sort of agree. Just thought I'd ask, do you have an opinion on what two slugs I should use here?

**Comment by ironunicorn** [comment]
I think it's fine in this case. Or maybe you could do something like
"thank_you_c3" and "thank_you_c4".

**Comment by DJ-Eckam** [comment]
Done; no git-managed changes were needed.
