### ISSUE TITLE
Post events to Facebook 

### ISSUE THREAD

**Issue by chrisflesher** [rcvfortexas/rcvfortexas#59]
From Harriet: Can you please keep track of new events posted on our website and create events for them on FB.

**Comment by chrisflesher** [comment]
Am wondering if there a way to do this automatically somehow?

**Comment by dsgit215** [comment]
I don't see anything in the NationBuilder support content about setting up automated FB posts for newly published events.  However, a Zap might work...if you want to invest in that service.  More info below.  This would need to be vetted by tech as I only have limited experience using Zaps under the "free" subscription level.  

https://zapier.com/apps/nationbuilder/integrations/facebook-pages

![image](https://user-images.githubusercontent.com/77990608/145919635-39aab37f-74af-4ae7-81ce-d2fd4ced6f44.png)

**Comment by DJ-Eckam** [comment]
It looks like Zapier would probably be able to create a Facebook *post* (linking to the event on our site) when an event is created, but I don't see anything about creating a Facebook *event*. 

One issue, if that were possible, would be what image to use on FB.

**Comment by chrisflesher** [comment]
It seems like a good idea to make NationBuilder events the "source of truth" and just have posts linking to them on Facebook. @DJ-Eckam are you mostly the one making events these days or is it John Thomson or someone else?

**Comment by DJ-Eckam** [comment]
It's not me, I don't know who is making events.

**Comment by dsgit215** [comment]
It looks like it's Harriet...unless someone else is using her NB profile.

**Comment by chrisflesher** [comment]
This got made into a procedure here:
https://docs.google.com/document/d/1HRaqPZ05-ZM_GwuecKIIUkyE5mFZZ7Vsz66EPxCv14A/edit
