### ISSUE TITLE
Email year-end donation reports

### ISSUE THREAD

**Issue by DJ-Eckam** [rcvfortexas/rcvfortexas#60]
Harriet asked for year-end donation reports. I sent the following to NB support:
Hello,

Could you tell me what is the best way to send donors a year-end summary of their donations? Preferably, it could be automatic and scheduled, but if that's not possible, whatever would work best.

We have two orgs for the website, with separate donation pages, one a C3 and the other C4. I think we will need to distinguish between those donation types.

If we can't do a year-end report, what about including year-to-date totals on each donation receipt?

Thanks!

**Comment by DJ-Eckam** [comment]
Here is the response I got from NB support:

Hi Dan,

Thanks for reaching out, thanks for your patience as well. There is a way to do this via customizing the source code in the email blast.

You will want to copy and paste the source code below in your email blast content editor.

<p>{{recipient.first_name_or_friend}} -- <br /><br />Here are your donations for the year:</p>

<p>&nbsp;</p>

<p>{% for donation in recipient.donations %}</p>

<p class="p1">{% assign donation_year = donation.succeeded_at | date: '%Y' %}</p>

<p class="p1">{% if donation_year == '2021' %}</p>

<table style="font-family: Helvetica, sans-serif; color: #000; font-size: 14px; line-height: 17px; border: 1px solid #E3E3E3; border-radius: 3px; margin-top: 40px;" border="0" cellspacing="0" cellpadding="0" width="600">

<tbody>

<tr>

<td>

<table border="0" cellspacing="0" cellpadding="0" width="600">

<tbody>

<tr>

<td align="left" style="padding: 16px; width: 50%; color: #707070;" valign="top"><strong style="color: #000000;">{{ site.long_name }}</strong> Receipt</td>

<td align="right" style="padding: 16px; width: 50%; color: #707070;" valign="top">Confirmation <strong style="color: #000000;"># {{ donation.id }}</strong></td>

</tr>

</tbody>

</table>

<table border="0" cellspacing="0" cellpadding="0" width="600">

<tbody>

<tr>

<td style="height: 1px; width: 100%; border-bottom: 1px solid #E3E3E3;">&nbsp;</td>

</tr>

</tbody>

</table>

{% if donation.is_recurring %}{% endif %}

<table border="0" cellspacing="0" cellpadding="0" width="600">

<tbody>

<tr>

<td align="left" style="padding: 9px; padding-left: 16px; padding-bottom: 16px; font-size: 12px; color: #707070;" width="110" valign="top"><strong>Date</strong></td>

<td style="padding: 9px; padding-bottom: 16px;" valign="top">{{ donation.succeeded_at | date_to_string }}</td>

</tr>

<tr>

<td align="left" style="padding: 9px; padding-left: 16px; font-size: 12px; color: #707070;" width="110" valign="top"><strong>Your info</strong></td>

<td style="padding: 9px;" valign="top">{{ donation.name }}<br />{{ donation.billing_address.one_line }}</td>

</tr>

<tr>

<td align="left" style="padding: 9px; padding-left: 16px; padding-top: 16px; font-size: 12px; color: #707070;" width="110" valign="top">&nbsp;</td>

<td style="padding: 9px; padding-top: 16px;" valign="top">{{ donation.billing_address.phone }}<br />{{ donation.email }}</td>

</tr>

<tr>

<td align="left" style="padding: 9px; padding-left: 16px; font-size: 12px; color: #707070;" width="110" valign="top">&nbsp;</td>

<td style="padding: 9px;" valign="top">{% if donation.employer.size &gt; 0 %}Employer: {{ donation.employer }}<br />{% endif %}{% if donation.occupation.size &gt; 0 %}Occupation: {{ donation.occupation }}{% endif %}</td>

</tr>

<tr>

<td align="left" style="padding: 9px; padding-left: 16px; padding-top: 16px; font-size: 12px; color: #707070;" width="110" valign="top"><strong>Amount</strong></td>

<td style="padding: 9px; padding-top: 16px;" valign="top"><strong style="font-size: 18px;">{{ donation.amount_format }}</strong> <span style="color: #00afbc;">Thank you!</span></td>

</tr>

<tr>

<td align="left" style="padding: 9px; padding-left: 16px; padding-top: 16px; font-size: 12px; color: #707070;" width="110" valign="top"><strong>Next bill date</strong></td>

<td style="padding: 9px; padding-top: 16px;" valign="top">{{ donation.next_billing_date | date_to_string }}</td>

</tr>

<tr>

<td align="left" style="padding: 9px; padding-left: 16px; padding-top: 16px; font-size: 12px; color: #707070;" width="110" valign="top"><strong>Paid by</strong></td>

<td style="padding: 9px; padding-top: 16px;" valign="top">{{ donation.payment_type_name }}</td>

</tr>

</tbody>

</table>

{% if donation.merchant_account %}

<table border="0" cellspacing="0" cellpadding="0" width="600">

<tbody>

<tr>

<td style="height: 1px; width: 100%; border-bottom: 1px solid #E3E3E3;">&nbsp;</td>

</tr>

</tbody>

</table>

<table border="0" cellspacing="0" cellpadding="0" width="600">

<tbody>

<tr>

<td style="padding: 16px;">This is {% if donation.merchant_account.is_taxable? == true %}not {% endif %}tax deductible</td>

</tr>

</tbody>

</table>

{% endif %}</td>

</tr>

</tbody>

</table>

<p>{% endif %}</p>

<p>{% endfor %}</p>

<p>Total amount donated this&nbsp; year:&nbsp;{{recipient.donations_amount_ytd_format}}<br /><br />{{broadcaster.name}}<br /><a href="{{settings.site.full_url}}">{{settings.site.full_url}}</a></p>

I hope that this helps. Please feel free to reach out should you have any additional questions.

Thank you,

Jazen Anderson

NationBuilder Support

**Comment by DJ-Eckam** [comment]
looks like it does not distinguish between our two entities, the c3 and the c4, and I suppose we need that.

**Comment by chrisflesher** [comment]
On the liquid page (https://nationbuilder.com/donation_variables) it says
there is a donation.tracking_code_slug. Wondering if we could use that
somehow?

**Comment by chrisflesher** [comment]
Maybe that variable would say what page the donation was made from?

**Comment by chrisflesher** [comment]
I tried this using NationBuilder filters and it looks like that variable will tell you whether or not the donation is tax deductible (donate) or non-tax deductable (donate_3). At least from the point where we set up the new donation pages...

**Comment by chrisflesher** [comment]
I think this is finished now?

**Comment by chrisflesher** [comment]
Dan says not yet.

**Comment by DJ-Eckam** [comment]
The email was sent today -- find it in the system as "Year 2021 Donation Report". Here are the main specs of the email, for future reference:
1. The recipients were defined as everybody who had made a donation during 2021. Harriet defined this group using tags, one for the one-time donors and another for recurring donors.
2. The group included some people who had not donated through the website but with a check. These donations were manually entered in NB, with a tracking code slug of either "donate" if to the 501c3, or "donate_3" if to the 501c4 -- the slugs match the page slugs for our Donate pages.
3. The email template uses some code that NB support helped me with. It loops through the data "recipient.donations" for each email recipient, and prints info for each donation if made in 2021. To report whether or not the donation was tax-deductible, it checks whether "donation.merchant_account" is defined and if so uses that -- each of our payment processors has a checkbox setting whether or not it is tax-deductible. If not defined, we check "donation.tracking_code_slug" which should have been defined for all manually entered donations. If neither is defined we are silent on the tax-deductibility.
4. The template contains a few occurrences of "2021" as a hard-coded string. These should all be updated if this template is used again for future years.
